TOOLKIT=$(PROGRAMFILES)\Civ4SDK\Microsoft Visual C++ Toolkit 2003
PSDK=$(PROGRAMFILES)\Civ4SDK\WindowsSDK
CIV4_PATH=$(PROGRAMFILES)\Steam\steamapps\common\Sid Meier's Civilization IV Beyond the Sword
#
# <!-- custom: note with the help of chatgpt thanks, also note below that Civ4Libs folder is just an example, it could be any folder name other than "Civ4Libs" and path other than program files if you prefer as long as it has the required Boost 1.32.0 and Python24 folders (and their files obviously not just empty folders), just i wanted them to be outside of git so that it doesn't clutter and in case we do manual backups too as i do quite some/many times. -->
# CIV4_LIB_INSTALL_PATH is not set here.
# Instead, it should be defined as a Windows environment variable.
# Example (permanent):
#   System Properties → Environment Variables → Add:
#     Name: CIV4_LIB_INSTALL_PATH
#     Value: C:\Program Files (x86)\Civ4Libs
# This is where Boost 1.32.0 and Python24 headers/libs must be placed.
#
# <!-- custom: note 1 also: i have not renamed mod name to AdvCiv-SAS in compiler files and such as may cause unexpected errors and our mod is fundamentally based on advciv mod so name is close enough, but the DLL is generated based on our real source files not base advciv ones i mean, just i am careful in this case to rather not rename mod name in compiler files or and such settings at least as of now, may change this later or maybe not since runs fine and does not seem to cause issues -->
#
# <!-- custom: note 2: unrelated but i would highly recommend after compile to delete the all the entire content in the (adjust to you mod path) C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization IV Beyond the Sword\Beyond the Sword\Mods\AdvCiv-SAS\CvGameCoreDLL\Project\temp_files\ folder, as if you don't, then the next compile will be a fastdep and this seems to cause weird issues ingame, see readme known issues in advciv-sas or your mod if it has this readme as well, so by deleting the folder after compuile it will do a full compile next time not a fast one based on precompiled stuff stored from last compile. -->
